// This file is auto-generated by scripts/generate-models.ts
// 本文件由 scripts/generate-models.ts 自动生成
// Do not edit manually - run 'npm run generate-models' to update
// 请勿手动编辑 —— 请运行 'npm run generate-models' 命令来更新

import values from "./data/azure-openai-responses.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const AZURE_OPENAI_RESPONSES_MODELS: ModelCatalog<typeof values, "azure-openai-responses"> =
	flattenModelCatalog("azure-openai-responses", values);
